const blogPostsdata = [
    {
    id: 1,
    title: 'Blog Post 1',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac lectus lobortis, lobortis purus sit amet, dictum risus. Aenean interdum, leo nec aliquet viverra, lectus justo fermentum purus, at laoreet odio lacus sed augue. Donec maximus sollicitudin arcu, id consectetur est aliquam ac. Fusce eget justo a sem rhoncus venenatis. In sed tortor nec risus lacinia consectetur. Sed viverra felis ac erat volutpat tincidunt. Curabitur tincidunt nunc sit amet tellus tincidunt, at tincidunt mauris interdum. Duis dictum, velit id tincidunt laoreet, neque neque aliquam sem, et lacinia eros tellus at ligula. Quisque eleifend, mi sit amet luctus congue, nibh enim viverra felis, non finibus erat nisl in justo',
    authorName: 'John Doe',
    topic: 'Technology',
    backgroundImage: "https://blogs.idc.com/wp-content/uploads/2023/05/eim-blog-header-image.png",
    },
    {
    id: 2,
    title: 'Blog Post 2',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac lectus lobortis, lobortis purus sit amet, dictum risus. Aenean interdum, leo nec aliquet viverra, lectus justo fermentum purus, at laoreet odio lacus sed augue. Donec maximus sollicitudin arcu, id consectetur est aliquam ac. Fusce eget justo a sem rhoncus venenatis. In sed tortor nec risus lacinia consectetur. Sed viverra felis ac erat volutpat tincidunt. Curabitur tincidunt nunc sit amet tellus tincidunt, at tincidunt mauris interdum. Duis dictum, velit id tincidunt laoreet, neque neque aliquam sem, et lacinia eros tellus at ligula. Quisque eleifend, mi sit amet luctus congue, nibh enim viverra felis, non finibus erat nisl in justo.',
    authorName: 'Jane Smith',
    topic: 'Travel',
    backgroundImage: "https://www.indiatravelblog.com/images/IndiaTravelBlog.jpg",
    },
    {
    id: 3,
    title: 'Blog Post 3',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac lectus lobortis, lobortis purus sit amet, dictum risus. Aenean interdum, leo nec aliquet viverra, lectus justo fermentum purus, at laoreet odio lacus sed augue. Donec maximus sollicitudin arcu, id consectetur est aliquam ac. Fusce eget justo a sem rhoncus venenatis. In sed tortor nec risus lacinia consectetur. Sed viverra felis ac erat volutpat tincidunt. Curabitur tincidunt nunc sit amet tellus tincidunt, at tincidunt mauris interdum. Duis dictum, velit id tincidunt laoreet, neque neque aliquam sem, et lacinia eros tellus at ligula. Quisque eleifend, mi sit amet luctus congue, nibh enim viverra felis, non finibus erat nisl in justo.',
    authorName: 'Michael Johnson',
    topic: 'Science',
    backgroundImage: "https://www.atascientific.com.au/wp-content/uploads/2018/11/final1.jpg",
    },
    {
    id: 4,
    title: 'Blog Post 4',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac lectus lobortis, lobortis purus sit amet, dictum risus. Aenean interdum, leo nec aliquet viverra, lectus justo fermentum purus, at laoreet odio lacus sed augue. Donec maximus sollicitudin arcu, id consectetur est aliquam ac. Fusce eget justo a sem rhoncus venenatis. In sed tortor nec risus lacinia consectetur. Sed viverra felis ac erat volutpat tincidunt. Curabitur tincidunt nunc sit amet tellus tincidunt, at tincidunt mauris interdum. Duis dictum, velit id tincidunt laoreet, neque neque aliquam sem, et lacinia eros tellus at ligula. Quisque eleifend, mi sit amet luctus congue, nibh enim viverra felis, non finibus erat nisl in justo.',
    authorName: 'Emily Wilson',
    topic: 'Food',
    backgroundImage: "https://www.justwords.in/wp-content/uploads/2020/10/indian-food-image.jpg",
    },
    {
    id: 5,
    title: 'Blog Post 5',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac lectus lobortis, lobortis purus sit amet, dictum risus. Aenean interdum, leo nec aliquet viverra, lectus justo fermentum purus, at laoreet odio lacus sed augue. Donec maximus sollicitudin arcu, id consectetur est aliquam ac. Fusce eget justo a sem rhoncus venenatis. In sed tortor nec risus lacinia consectetur. Sed viverra felis ac erat volutpat tincidunt. Curabitur tincidunt nunc sit amet tellus tincidunt, at tincidunt mauris interdum. Duis dictum, velit id tincidunt laoreet, neque neque aliquam sem, et lacinia eros tellus at ligula. Quisque eleifend, mi sit amet luctus congue, nibh enim viverra felis, non finibus erat nisl in justo.',
    authorName: 'David Thompson',
    topic: 'Health',
    backgroundImage: "https://www.metropolisindia.com/blog/wp-content/uploads/2021/08/assess_heart_health.jpg",
    },
    {
    id: 6,
    title: 'Blog Post 6',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac lectus lobortis, lobortis purus sit amet, dictum risus. Aenean interdum, leo nec aliquet viverra, lectus justo fermentum purus, at laoreet odio lacus sed augue. Donec maximus sollicitudin arcu, id consectetur est aliquam ac. Fusce eget justo a sem rhoncus venenatis. In sed tortor nec risus lacinia consectetur. Sed viverra felis ac erat volutpat tincidunt. Curabitur tincidunt nunc sit amet tellus tincidunt, at tincidunt mauris interdum. Duis dictum, velit id tincidunt laoreet, neque neque aliquam sem, et lacinia eros tellus at ligula. Quisque eleifend, mi sit amet luctus congue, nibh enim viverra felis, non finibus erat nisl in justo.',
    authorName: 'Sarah Adams',
    topic: 'Fashion',
    backgroundImage: "https://img-c.udemycdn.com/course/750x422/442714_0bd4_4.jpg",
    },
]
export default blogPostsdata;